# Generated by Django 3.0.5 on 2020-12-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=55, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        # migrations.CreateModel(
        #     name='User',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('user_first_name', models.CharField(blank=True, max_length=55, null=True)),
        #         ('user_last_name', models.CharField(blank=True, max_length=55, null=True)),
        #         ('user_email', models.EmailField(blank=True, max_length=55, null=True)),
        #         ('user_class', models.TextField(blank=True, null=True)),
        #         ('user_password', models.CharField(blank=True, max_length=255, null=True)),
        #         ('user_role_id', models.IntegerField(null=True)),
        #         ('create_at', models.DateTimeField(auto_now_add=True)),
        #         ('update_at', models.DateTimeField(auto_now=True)),
        #     ],
        #     options={
        #         'db_table': 'users',
        #     },
        # ),
    ]
