# Generated by Django 3.0.5 on 2021-01-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(blank=True, max_length=55, null=True)),
                ('school_director', models.CharField(blank=True, max_length=55, null=True)),
                ('school_pic_director', models.ImageField(blank=True, default='school/no_img.png', null=True, upload_to='school')),
                ('school_profile_school', models.TextField(blank=True, null=True)),
                ('school_province', models.CharField(blank=True, max_length=55, null=True)),
                ('school_district', models.CharField(blank=True, max_length=55, null=True)),
                ('school_sub_district', models.CharField(blank=True, max_length=55, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_key', models.TextField(blank=True, null=True)),
                ('token_user_id', models.IntegerField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
    ]
