# Generated by Django 3.0.5 on 2021-01-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSAPI', '0002_schools_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(blank=True, max_length=55, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=55, null=True)),
                ('user_gender', models.IntegerField(null=True)),
                ('user_email', models.EmailField(blank=True, max_length=55, null=True)),
                ('user_class', models.TextField(blank=True, null=True)),
                ('user_password', models.CharField(blank=True, max_length=255, null=True)),
                ('user_school_id', models.IntegerField(null=True)),
                ('user_role_id', models.IntegerField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
