# Generated by Django 3.0.5 on 2021-01-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSAPI', '0006_quiz_quiz_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_proposition', models.TextField(blank=True, null=True)),
                ('quiz_choice', models.TextField(blank=True, null=True)),
                ('quiz_score', models.FloatField(null=True)),
                ('quiz_score_per_ans', models.FloatField(null=True)),
                ('quiz_skill_id', models.IntegerField(null=True)),
                ('quiz_quiz_set_id', models.IntegerField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
    ]
