# Generated by Django 3.0.5 on 2021-01-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSAPI', '0007_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSave',
            fields=[
                ('quiz_save_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_save_quiz_id', models.IntegerField(null=True)),
                ('quiz_save_score', models.FloatField(null=True)),
                ('quiz_save_user_id', models.IntegerField(null=True)),
                ('quiz_save_count', models.IntegerField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quiz_save',
            },
        ),
    ]
