# Generated by Django 3.0.5 on 2021-01-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITSAPI', '0008_quizsave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizSave',
        ),
    ]
