# Generated by Django 3.0.5 on 2021-01-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSAPI', '0010_quizsave'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalScore',
            fields=[
                ('total_score_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_score_percent', models.FloatField(null=True)),
                ('total_score_male', models.FloatField(null=True)),
                ('total_score_female', models.FloatField(null=True)),
                ('total_score_skill_id', models.IntegerField(null=True)),
                ('total_score_school_id', models.IntegerField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'total_score',
            },
        ),
    ]
