from django.urls import path
from .views import *

urlpatterns = [
    path('create_Role', CreateRole.as_view()),
    path('get_role', GetRole.as_view()),
    path('Register', CreateUserITS.as_view()),
    path('Login', LoginITS.as_view()),
    path('create_school', CreateSchool.as_view()),
    path('update_school', UpdateSchool.as_view()),
    path('get_school_guest', GetSchoolForGuest.as_view()),
    path('get_school_all_guest', GetSchoolAllGUEST.as_view()),
    path('get_school_all', GetSchoolAll.as_view()),
    path('get_school/school_id/<int:school_id>', GetSchoolById.as_view()),
    path('create_skill', CreateSkill.as_view()),
    path('update_skill', UpdateSkill.as_view()),
    path('get_skill', GetSkill.as_view()),
    path('create_quiz_set', CreateQuizSet.as_view()),
    path('update_quiz_set', UpdateQuizSet.as_view()),
    path('get_quiz_set', GetQuizSet.as_view()),
    path('create_quiz', CreateQuiz.as_view()),
    path('update_quiz', UpdateQuiz.as_view()),
    path('get_quiz/quiz_set_id/<int:quiz_set_id>', GetQuizBySetId.as_view()),
    path('get_quiz/quiz_id/<int:quiz_id>', GetQuizById.as_view()),
    path('save_quiz', QuizAnsSave.as_view()),
    path('get_score_total', GetScoreTotal.as_view()),
    path('get_score_total/school_id/<int:school_id>', GetScoreTotalBySchoolID.as_view()),
    path('get_score_total_answer', GetAnswerScoreTotal.as_view()),
    path('get_score_by_school_id/<int:school_id>', GetScoreBySchool.as_view()),
    path('get_score_by_user_id/<int:user_idt>', GetScoreByUserName.as_view()),
    path('get_address_by_school', GetAddressSchool.as_view()),
    path('get_quiz_by_Id_only_setquiz/<int:quiz_id>', GetQuizByIdOnlySetQuiz.as_view()),
    path('get_quiz_for_test/<int:quiz_set_id>', GetQuizForTest.as_view()),
    path('get_time_quiz', GetTimeQuiz.as_view()),
    path('create_choice_test_mode', ChoiceTestModeSave.as_view()),
    path('get_choice_test_mode_all', GetChoiceTestModeAll.as_view()),
    path('get_choice_test_mode_by_id/<int:test_id>', GetChoiceTestModeByID.as_view()),
    path('update_choice_test_mode', UpdateChoiceTestMode.as_view()),
    path('get_answer_score_testmode/<int:quiz_set_id>', GetAnswerScoreTest.as_view()),
    path('reset_password', ResetPassword.as_view()),
    path('ans_reset_password', AnsResetPassword.as_view()),
    path('del_quiz_set',DeleteQuizSet.as_view()),
    path('del_skill',DeleteSkill.as_view()),
    path('del_school',DeleteSchool.as_view()),
    path('del_quiz',DeleteQuiz.as_view()),
    path('update_user',UpdateUser.as_view()),

]